version: 2.1
 
orbs:
 aws-cli: circleci/aws-cli@3.1.3
 
workflows:
  clean_test_build_&_deploy:
    jobs:
      - build
      - deploy:
            requires:
              - build


jobs:

 build:  # name of job
  working_directory: ~/dominos
  executor: aws-cli/default
  steps:
    - checkout:
        path: ~/dominos
    - aws-cli/setup:
        aws-access-key-id: AWS_ACCESS_KEY
        aws-secret-access-key: AWS_SECRET_KEY
        aws-region: AWS_REGION_NAME
    - setup_remote_docker:
        version: 20.10.14
    - run:
       name: "Building Docker Image"
       command: docker build -t $ECR_REGISTRY/$APP_NAME:$IMAGE_TAG_CLIENT .
    - run:
       name: "ECR Login"
       command: aws ecr get-login-password | docker login --username AWS --password-stdin $ECR_REGISTRY
    - run:
       name: "Pushing  Image into Amazon Elastic Container"
       command: docker push $ECR_REGISTRY/$APP_NAME:$IMAGE_TAG_CLIENT
 
 
 


 deploy:
   machine:
     image: ubuntu-2004:202010-01
   steps:
     - add_ssh_keys:
         fingerprints:
           - "9b:1c:e9:f7:60:77:23:2a:38:25:bf:bf:b1:04:37:34"
     - run:
         name: "Deploying the app into AWS EC2"
         command: |
                 ssh -v -o StrictHostKeyChecking=no ec2-user@65.1.111.150 "
                 aws ecr get-login-password --region ap-south-1 | docker login --username AWS --password-stdin $ECR_REGISTRY &&                  
                 docker ps -aq | xargs docker stop | xargs docker rm &&
                 docker images -aq | xargs docker image rm &&
                 docker run -d -p 3000:3000 $ECR_REGISTRY/$APP_NAME:$IMAGE_TAG_CLIENT "


# VS Code Extension Version: 1.0.2
